CREATE DATABASE StudentDB;
GO
USE StudentDB;
GO
CREATE TABLE Students (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100),
    Email NVARCHAR(100),
    Address NVARCHAR(200),
    Age INT,
    Grade NVARCHAR(50)
);